FROM alpine:3.19 AS bb
RUN apk add --no-cache busybox-static

FROM langflowai/langflow:1.2.0

COPY --from=bb /bin/busybox /usr/local/bin/busybox
RUN ln -sf /usr/local/bin/busybox /usr/local/bin/nc && \
    mkdir -p /opt/webdata

