FROM ubuntu:22.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y samba smbclient && useradd -m filesvc

RUN mkdir -p /srv/samba/hr && \
    echo "name,salary\nAlice,100000\nBob,90000" > /srv/samba/hr/salary_list.csv && \
    chown -R filesvc:filesvc /srv/samba

COPY smb_smb.conf /etc/samba/smb.conf

CMD service smbd restart && tail -f /dev/null
